### ISSUE TITLE
404 Error: ENOENT, stat when starting app local

### ISSUE THREAD

**Issue by AlexChar** [notorii/generator-mean-seed#21]
Connect
404 Error: ENOENT, stat 'C:\Users\websites\mean-company\app\src\index.html'
   at Error (native)

**Comment by lukemadera** [comment]
@AlexChar sorry for the very slow reply - are you still having this issue? I'm assuming you ran `grunt` and checked that the file exists on your computer?

**Comment by AlexChar** [comment]
@lukemadera  thanks for the reply. I will check it again.

**Comment by AlexChar** [comment]
@lukemadera  you are right index.html doesn't exist in this path. Should I add it? Assuming the generator create all necessary files?

**Comment by lukemadera** [comment]
@AlexChar index.html is a file auto generated by grunt. Run `grunt q` and it will create `index.html` from `index-grunt.html`

**Comment by AlexChar** [comment]
@lukemadera  sorry for the late response. This time everything worked fine. Thanks a lot(didn't run `grunt q`).
