### ISSUE TITLE
ng-route seed not working

### ISSUE THREAD

**Issue by ronalds1** [notorii/generator-mean-seed#24]
i run 'yo mean-seed' and selected 'ng-route', entered 'locationmap' as new page name and giving the error:

C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_m
odules\rx\dist\rx.js:579
    throw e;
          ^
TypeError: Cannot call method 'camelize' of undefined

any ideas ?

**Comment by lukemadera** [comment]
Seems like the underscore dependency was missing. I just added it and pushed an update - could you try again? And if that still does not work, try installing underscore globally and then see if it works?
@ronalds1

**Comment by lukemadera** [comment]
Actually, this should be fixed by https://github.com/notorii/generator-mean-seed/issues/19
