### ISSUE TITLE
yo mean-seed fails in ejs templating

### ISSUE THREAD

**Issue by bennyrowland** [notorii/generator-mean-seed#25]
Created a brand new virtual machine on ubuntu 14.04 and followed all instructions to install dependencies and get started. At the point where I run "yo mean-seed" it fails with various errors relating to the ejs templating step. The first problem is that it complains print is not defined on the lines such as
```<%
    if(optCssPreprocessor =='less') {
        print('...');
    }
%>
```
This I solved by using a variable as an intermediate step and outputting that afterwards:
```<%
    if(optCssPreprocessor =='less') {
        var output = '...';
    }
%>
<%= output %>
```
The next problem arises in the _Gruntfile.js where an error like this appears:
```Error: Could not find matching close tag for "<%".
    at /usr/lib/node_modules/ejs/lib/ejs.js:506:19```
which comes from the fact that inside one of the print strings are some nested <%%= %> which do not seem to be allowed by ejs. I was able to solve this problem by a more complicated pattern of switching in and out of ejs tags like so:
```
<% if(optCssPreprocessor=='less') { %>
... // plain javascript rather than inside string, but containing <%%= %> tags
<%}
else if ...
%>
```
The current error that I can't get past comes from templating realtime.js:
```events.js:72
        throw er; // Unhandled 'error' event
              ^
ReferenceError: /usr/lib/node_modules/generator-mean-seed/core-default-node/templates/app/modules/services/realtime/realtime.js:6
    4| 
    5| NOTE: make sure to include the socket.io client side script on the frontend (i.e. in index.html), i.e. (for grunt templated version)
 >> 6| <%
    7| var cfgJson = grunt.config('cfgJson');
    8|     print('\t<script type="text/javascript" src="'+cfgJson.server.scheme+'://'+cfgJson.server.domain+':'+cfgJson.server.socketPort+'/socket.io/socket.io.js"></script>\n');
    9| %>

grunt is not defined
```
I suspect that these problems are caused by using a different version of some package or other, I also receive a lot of warnings of this type:
```
(!) generator#invoke() is deprecated. Use generator#composeWith() - see http://yeoman.io/authoring/composability.html
   invoke   mean-seed:core-default-node
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
```
when running yo mean-seed. Any assistance figuring this out would be greatly appreciated.

**Comment by bennyrowland** [comment]
Ok, so I made some more progress. It turns out that the relevant grunt command is in a block comment in the file so it doesn't need to be run anyway. Removing that code allows the ejs section to complete and the rest of the directories from the core-default-node index.js are copied across. Unfortunately I immediately get another error
```
(!) generator#invoke() is deprecated. Use generator#composeWith() - see http://yeoman.io/authoring/composability.html

SyntaxError: Unexpected token &
    at Object.parse (native)
    at EditionInterface.module.exports [as readJSON] (/usr/lib/node_modules/generator-mean-seed/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/read-json.js:5:17)
    at CoreDefaultAngularGenerator.Base.determineAppname (/usr/lib/node_modules/generator-mean-seed/node_modules/yeoman-generator/lib/base.js:756:23)
    at CoreDefaultAngularGenerator.Base (/usr/lib/node_modules/generator-mean-seed/node_modules/yeoman-generator/lib/base.js:152:23)
    at CoreDefaultAngularGenerator.module.exports.Base.extend.constructor (/usr/lib/node_modules/generator-mean-seed/node_modules/yeoman-generator/lib/named-base.js:19:10)
    at new CoreDefaultAngularGenerator (/usr/lib/node_modules/generator-mean-seed/core-default-angular/index.js:22:30)
    at Environment.instantiate (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:282:10)
    at Environment.create (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:259:15)
    at MeanSeedGenerator.invoke (/usr/lib/node_modules/generator-mean-seed/node_modules/yeoman-generator/lib/actions/invoke.js:26:23)
    at MeanSeedGenerator.invoke (/usr/lib/node_modules/generator-mean-seed/node_modules/yeoman-generator/lib/util/deprecate.js:8:15)
```

I don't know what file is being loaded at this point and therefore can't check what is causing the error.

**Comment by lukemadera** [comment]
Hmm odd. Does seem like a dependency versioning issue. I set the dependencies explicitly so they should match and I'm not having those issues nor I have heard of anyone else having them. Did you globally install any of the dependencies (i.e. grunt) at different versions and those could be conflicting?
@bennyrowland

**Comment by bennyrowland** [comment]
I installed Ubuntu 14.04 in a new virtual machine and then the only things I did were to run the commands listed in the documentation. Is it possible that it is npm or yo which are too recent?

**Comment by lukemadera** [comment]
Might by related to https://github.com/notorii/generator-mean-seed/issues/19
