### ISSUE TITLE
Cloned repositiory doesn't display user info on dev-test page

### ISSUE THREAD

**Issue by awaemmanuel** [notorii/generator-mean-seed#26]
Hello Luke, 

I don't know if this is a known issue, but once I clone the generator repository, start mongo and run node run.js on a new machine, I always get {"_id":false}..

I have users on the mongo db and I've verified this.

> use mean-company
switched to db mean-company
> db.user.find()
{ "_id" : ObjectId("5572f183a0828b084100ba89"), "email" : "go@go.com", "password" : "265182cf6aab85d90959239613608bc6e8e15484", "first_name" : "Places", "last_name" : "Gone", "status" : "member", "social" : {  }, "signup_method" : "email", "emails_all" : [ { "email" : "go@go.com", "confirmed" : 0, "primary" : 1 } ], "password_salt" : "CkLDNohvoudHiDks", "sess_id" : [ "WUII4x2ywSBGqsnN" ], "signup" : "2015-06-06 09:11:31", "last_login" : "2015-06-06 09:11:31" }
>

angular.module('myApp').controller('TestCtrl', ['$scope', '$timeout', 'appHttp', 'UserModel', '$location', '$q', function($scope, $timeout, appHttp, UserModel, $location, $q) {
	$scope.log = [];
	function logit(text, params) {
		console.log('logit', + text);
		$scope.log.push(text);
	}
    $scope.$on('appMyDirectiveEvt1', function(evt, params) {
		logit('controller directive event');
    });

    $scope.funcOne = function() {
        logit('funcOne controller');
    };

	$scope.scopeOne = 'scope one is here now';
	$scope.myVar = 'var13333';
	$scope.user =UserModel.load();

....
}

**Comment by lukemadera** [comment]
yep, not an issue, it's just showing that there's no user logged in yet (hence _id: false)!
