### ISSUE TITLE
node.js is "outdated"

### ISSUE THREAD

**Issue by joseph-d** [notorii/generator-mean-seed#27]
Hi Luke,

I've come across this git repo because I'm following your videos on masteringmean.com.

I have followed your instructions but things start to go wrong right at the beginning when installing yo:

`npm WARN engine yo@1.4.7: wanted: {"node":">=0.10.0","npm":">=2.8.0"} (current: {"node":"0.10.35","npm":"1.4.28"})`

This is confirmed further down when the Yeoman Doctor runs:

`Your Node.js version is outdated.
Upgrade to the latest version: https://nodejs.org`

The thing is, it seems like Yeoman actually wants an *older* version rather than a newer version.

Anyway, at the end of the installation, I get `Found potential issues on your machine :(` followed by trees of all of the packages installed.

Despite the errors, I tried `npm install -g generator-mean-seed` anyway and it worked. However, `yo --help` doesn't list any generators, meaning that `yo mean-seed` doesn't work either.

**Comment by joseph-d** [comment]
Glad I didn't pay for the masteringmean.com course!

**Comment by Blueblau** [comment]
Just had the same issue. Download the latest stable version, not v4.x.x but v5.x.x...

Latest is 5.4.0 at this time of writing.
