### ISSUE TITLE
Error after "Done, without errors" when running "yo mean-seed" (Ubuntu)

### ISSUE THREAD

**Issue by kierer** [notorii/generator-mean-seed#29]
I'm running under Ubuntu 15.04 and get the following error at the very end of the generation process:

Done, without errors.
child process exited with code: 0
command run and done: grunt args: q
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn ./node_modules/protractor/bin/webdriver-manager update ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

If I manually run './node_modules/protractor/bin/webdriver-manager update', selenium and chromedriver update successfully.

**Comment by wligtenberg** [comment]
I ran into a similar issue, not 100% sure it is the same, but in my case running grunt dev also didn't find the selenium stuff.

My error is the following:
Done, without errors.
child process exited with code: 0
command run and done: grunt args: q

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by ryanple** [comment]
I run into the same as wligtenberg (events.js:72) on Ubuntu 15.04; all my permissions are good as everything else installed fine. I'm assuming it's not a big deal if it was closed then, Luke?

**Comment by lukemadera** [comment]
Yes I believe so, as long as you run './node_modules/protractor/bin/webdriver-manager update', selenium and chromedriver update successfully BEFORE you run grunt, as per the instructions.
